# Generated by Django 6.0.6 on 2026-07-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_label', models.CharField(default='sample_data/transactions.json', max_length=255)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('total_valid', models.PositiveIntegerField(default=0)),
                ('total_invalid', models.PositiveIntegerField(default=0)),
                ('status_counts', models.JSONField(default=dict)),
                ('currency_totals', models.JSONField(default=dict)),
                ('error_type_counts', models.JSONField(default=dict)),
                ('source_counts', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('error_type', models.CharField(db_index=True, max_length=100)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('raw_record', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='transactions.processingrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], db_index=True, max_length=10)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.processingrun')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['status', 'currency'], name='transaction_status_b81d78_idx')],
            },
        ),
    ]
